server:
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.angolodivino: INFO

management:
  endpoint:
    health:
      show-details: never

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
